[package]
name = "day_07"
version = "0.1.0"
authors = ["Michal Stolarczyk <michal.stolarczyk@workday.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcre = "0.2.3"
